name: "Poly Notify"
description: "Send status updates to Slack, Twilio, and Discord"
inputs:
  twilio_account_sid:
    description: "Your Twilio Account SID. Available at https://www.twilio.com/console/project/settings."
    required: false
  twilio_api_key_sid:
    description: "Your Twilio API Key's SID. Available at https://www.twilio.com/console/project/api-keys."
    required: false
  twilio_api_key_secret:
    description: "Your Twilio API Key's secret. Only available when the API is first created at https://www.twilio.com/console/project/api-keys."
    required: false
  twilio_from_number:
    description: "The phone number, in E164 format.\nSee https://support.twilio.com/hc/en-us/articles/223183008-Formatting-International-Phone-Numbers."
    required: false
  twilio_to_numbers:
    description: "The phone numbers (separated by commas) to send the message to. Also in E164 format."
    required: false
  slack_bot_token:
    description: "A Slack Bot API token. See https://api.slack.com/docs/token-types for more info. Note that this overrides slack_webhook_url."
    required: false
  slack_username:
    description: "The username to post Slack messages as."
    required: false
  slack_icon_url:
    description: "The URL of an image to use as the Slack avatar. Only works when slack_username is also set."
    required: false
  slack_channel_name:
    description: "The name of the Slack channel to post in. Only works with slack_bot_token."
    required: false
  slack_message_id:
    description: "The ID of an existing Slack message, in the slack_channel_name, to update. If present, this message will be changed to the new content rather that a new message being posted."
    required: false
  discord_webhook_url:
    description: "The URL of your Discord channel webhook. You can create this in the settings for the channel you wish to post in."
    required: false
  discord_username:
    description: "The username to post to Discord as. Defaults to an empty string, which uses the username you configured your webhook with."
    required: false
    default: ""
  discord_avatar:
    description: "The URL to the avatar to post to Discord with. Defaults to an empty string, which uses the avatar you configured your webhook with."
    default: ""
  color:
    description: "A hex color to use with Slack and Discord messages."
    required: false
    default: ""
  message:
    description: "The message you want to send. A link to the GitHub event that triggered this action will be added automatically."
    required: true
  fail_on_error:
    description: "By default this action will not register an error on the workflow if it fails. Set this to true to change that behavior."
    required: false
    default: false
outputs:
  twilio_result:
    description: The outputs of the Twilio API calls
  slack_message_id:
    description: The timestamp/ID of the Slack message. Can be passed back to later invocations to update the original message.
  discord_result:
    description: The output of the Discord API call
runs:
  using: "node12"
  main: "index.js"
